services:
    app:
        container_name: ${CONTAINER_NAME:-kingsraid}
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - ${DOCKER_PORT:-3000}:3000
        restart: unless-stopped
