services:
    app:
        image: ghcr.io/faberuser/kingsraid:latest
        container_name: ${CONTAINER_NAME:-kingsraid}
        build:
            context: .
            dockerfile: Dockerfile
            # args:
            #     - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
        ports:
            - ${DOCKER_PORT:-3000}:3000
        restart: unless-stopped
