services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL:-https://kingsraid.k-clowd.top}
                - NEXT_PUBLIC_ENABLE_MODELS_VOICES=${NEXT_PUBLIC_ENABLE_MODELS_VOICES:-false}
